site_name: 'SnappyRouter'
pages:
-   ['index.md', 'Home', 'Home']
-   ['getting_started.md', 'Home', 'Getting Started']
-   ['handlers/index.md', 'Handlers', 'Handlers']
-   ['handlers/controller_handler.md', 'Handlers', 'Controller Handler']
-   ['handlers/rest_handler.md', 'Handlers', 'Rest Handler']
-   ['handlers/pattern_handler.md', 'Handlers', 'Pattern Match Handler']
-   ['handlers/direct_handler.md', 'Handlers', 'Direct Script Handler']
-   ['handlers/cli_handler.md', 'Handlers', 'CLI Task Handler']
-   ['plugins/index.md', 'Plugins', 'Plugins']
-   ['di.md', 'Dependency Injection', 'Dependency Injection']
theme: 'readthedocs'
